########################################################################################
#                                                                                      #
#                        _____      _   _   _                                          #
#                       / ____|    | | | | (_)                                         #
#                      | (___   ___| |_| |_ _ _ __   __ _ ___                          #
#                       \___ \ / _ \ __| __| | '_ \ / _` / __|                         #
#                       ____) |  __/ |_| |_| | | | | (_| \__ \                         #
#                      |_____/ \___|\__|\__|_|_| |_|\__, |___/                         #
#                                                    __/ |                             #
#                                                   |___/                              #
#                                                                                      #
########################################################################################

# Welcome to the Settings file. In this file you can change many things that are within the plugin.
# If you have questions about how to use this file, please don't hesitate to PM me (_ItsShadow_)
# on Spigot or on Discord (Schatten#4113)
# If you want to change anything that has to due with messages edit the 'messages.yml' file.
# If you want to add items to the inventory edit the 'inventory.yml' file.

# This config is applicable to auto update entries. If I add another entry to this file it will be applied when you
# update the plugin. It is recommended that you backup your file before updating the plugin.

# Should we use notify administrator (with the permission punishgui.admin.update) when an update is available?
use-updater: true

# Should we use sounds in the plugin?
use-sounds: false

# Use random sound pitches?
use-random-sound-pitch: true

# Should restrict access to some items, to people that don't have the permission defined in the 'permission' entry for an item?
permission-items: true

# This will print messages to console that are useful to the developer. Unless you want to have many messages in console
# I don't suggest you enable this.
debug: false

# If enabled the plugin will send statistics to BStats. Which you can see here: https://bstats.org/plugin/bukkit/PunishGUI
metrics: true

# This is what we use when the command isn't passed a reason.
default-reason: "Something, I can't remember what though."

########################################################################################
#                                                                                      #
#                                 Inventory Stuffs                                     #
#                                                                                      #
# Different Materials                                                                  #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html                    #
########################################################################################

# By default we disallow shift clicking because when we allowed shift clicking in the menu,
# I encountered an error that would allow the player to get the item in their inventory when shift clicking items.
disallow-shiftclicking: true

# The name of the inventory.
punish-inv-name: "&6You are punishing &e{target}" # You can only use the {target} placeholder here.

# The size of the inventory. This can be a max of 54 and a minimum of 9. All entries have to be a multiple of nine.
inv-size: 27

# Should we set empty panels in the menu to something?
fill-spare-inv-spaces: true

# This only applies if the above is true.
fill-item: GRAY_STAINED_GLASS_PANE

########################################################################################
#                                                                                      #
#                                      Sounds                                          #
#                                                                                      #
# Want to use different sounds?                                                        #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html                       #
########################################################################################

# Change the pitch of the sound that plays.
# (This is overridden if use-random-sound-pitch is set to 'true')
# 0 is low, 1 is normal, 2 is high.
sound-pitch: 1

# The sound that will play when a player runs the command '/punish'
punish-open-sound: ENTITY_ARROW_HIT_PLAYER

# The sound that will be played to players that can receive the update notifications.
update-available-sound: ENTITY_EVOKER_CAST_SPELL
